#!/usr/bin/env bash
# Configures an Ubuntu server with Nginx and adds a custom X-Served-By header

# Update package lists and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Inject the custom header line into the default server configuration block
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
