#!/usr/bin/env bash
# Configures a fresh Ubuntu server with an Nginx landing page

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
